text = 'Это моя строка'
print('Вывод 1')
print(text[0])
print('Вывод 2')
print(text[-1])
print('Вывод 3')
print(text[2:5])
print('Вывод 4')
print(text[::-1])
print('Вывод 5')
print(len(text))
print('Вывод 6')
print('Это новая строка ' + text)
